# Generated by Django 4.0.1 on 2022-01-18 17:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anuncio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("foto", models.ImageField(upload_to="")),
                ("localizacao", models.CharField(max_length=200)),
                ("preco", models.FloatField()),
                ("locador", models.CharField(max_length=50)),
                ("data_post", models.DateField(auto_now=True)),
                ("alugado", models.BooleanField(default=False)),
                (
                    "telefone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
            ],
        ),
    ]
