# Generated by Django 4.0.1 on 2022-03-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anuncio", "0017_alter_anuncio_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anuncio",
            name="foto",
            field=models.ImageField(upload_to=""),
        ),
    ]
